PazarSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from accounts.views import activation_sent_view, activate, ProfileEditView, ProfileView, post_comment_create_and_list_view, like, unlike, favourite, PostDetail, likePost, unlikePost, tags, PostDeleteView, PostEditView, showNotifications, DeleteNotification

admin.site.site_header = "Pazar Admin"
admin.site.site_title = "Pazar Admin Portal"
admin.site.index_title = "Welcome to Pazar Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pazar.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),

    path('accounts/', include('allauth.urls')),
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='pazar/change-password.html',success_url='home'),name='change-password'),

    path('edit-profile/', ProfileEditView.as_view(), name="edit-profile"),
    path('profile/<int:id>/<slug:slug>', ProfileView.as_view(), name="profile"),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name="password_change"),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('posts/', post_comment_create_and_list_view, name="posts"),
    path('post/like/<int:pk>', like, name="like-post"),
    path('post/unlike/<int:pk>', unlike, name="unlike-post"),
    path('like-post/<int:pk>', likePost, name='like'),
    path('unlike-post/<int:pk>', unlikePost, name='unlike'),
    path('post/favourite/<int:pk>', favourite, name='favourite'),
    path('post/<int:pk>', PostDetail, name='post-detail'),
    path('post/tags/<slug:slug>', tags, name="tag"),
    path('post/<int:pk>/edit', PostEditView.as_view(), name="post-edit"),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('posts/notifications', showNotifications, name='show-notifications'),
    path('posts/notifications/<int:pk>/delete', DeleteNotification, name="delete-notification"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.http import HttpResponse
from .import views
from .views import ShopOwnerSignUpView, UserSignUpView, LoginView, ConsumerInterestsView

urlpatterns = [
    path('signup/', views.SignUpView, name='signup'),
    path('signup/business_owner/', views.ShopOwnerSignUpView, name='business_owner_signup'),
    path('signup/user/', views.UserSignUpView, name='user_signup'),
    path('login', LoginView.as_view(), name="login"),
    path('interests/', ConsumerInterestsView.as_view(), name='Consumer_interests'),
    path('profile/<slug:slug>', views.ProfileDetailView.as_view(), name="profile-detail"),
]

blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.bloghome, name="blog_home"),
    path('category/<slug:slug>', views.blogcategory, name="blog_category"),
    path('all-category', views.category, name="all_category"),
    path('article/<slug:slug>', views.blogPost, name="blog-post"),
    path('postComment', views.postComment, name="postComment"),
    path('tag/<slug:slug>/', views.tagged, name="tagged"),
    path('write-for-us', views.writeForUs, name="writeForUs"),
    path('search', views.search, name="search"),
    path('edit/<slug:slug>', views.BlogEditView.as_view(), name="edit-blog"),
    path('delete/<slug:slug>', views.BlogDeleteView.as_view(), name="delete-blog"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager
from django.core.validators import RegexValidator, MinValueValidator, FileExtensionValidator
from pazar.models import Category
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.conf import settings
import os
from taggit.managers import TaggableManager
from django.db.models.signals import post_save, post_delete

USERNAME_REGEX = '^[a-zA-Z0-9.+-]*$'

def user_profile_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    profile_pic_name = 'user_{0}/profile.jpg'.format(instance.user.id)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_pic_name)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return profile_pic_name

def post_image_directory_path(instance, filename):
    return 'user_{0}/post/{1}/{2}'.format(instance.uploaded_by.id, instance.msg, filename)

def post_images_directory_path(instance, filename):
    return 'user_{0}/post/{1}/{2}'.format(instance.post.uploaded_by.id, instance.post.msg, filename)

def post_multiple_images_directory_path(instance, filename):
    return 'user_{0}/post/{1}multiple_images/{2}'.format(instance.user.id, instance.post.msg, filename)

# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self,email,password,**extra_fields):
        if not email:
            raise ValueError(_('The email must be set.'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self,email,password,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_active',True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email,password,**extra_fields)

class CustomUser(AbstractUser):
    username = models.CharField(max_length=150, validators=[RegexValidator(regex=USERNAME_REGEX)], unique=True, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.')
    email = models.EmailField(_('E-Mail'), unique=True)
    is_shop_owner = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    signup_confirmation = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.username

    def get_short_name(self):
        return self.username

class ShopOwner(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Consumer(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    interests = models.ManyToManyField(Category, related_name='Interested_Category')

    def __str__(self):
        return self.user.username
    
class Profile(models.Model):
    name = models.CharField(max_length=100)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, blank=True)
    age = models.IntegerField(default=18, validators=[MinValueValidator(18)])
    birthday = models.DateField(null=True, blank=True)
    gender = models.CharField(
        max_length=20, default="Male", choices=(("Male", "Male"), ("Female", "Female"))
    )
    bio = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=1000, null=True, blank=True)
    address = models.CharField(max_length=250,null=True, blank=True)
    phone_no = models.CharField(
        validators=[RegexValidator("0?[5-9]{1}\d{9}$")],
        max_length=15,
        null=True,
        blank=True,
    )
    website = models.URLField(null=True, blank=True, default="")
    facebook = models.URLField(null=True, blank=True, default="")
    instagram = models.URLField(null=True, blank=True, default="")
    twitter = models.URLField(null=True, blank=True, default="")
    github = models.URLField(null=True, blank=True, default="")
    linkedin = models.URLField(null=True, blank=True, default="")
    youtube = models.URLField(null=True, blank=True, default="")
    pinterest = models.URLField(null=True, blank=True, default="")
    pic = models.ImageField(
        upload_to=user_profile_directory_path, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], default="Default User.png", null=True, blank=True
    )
    favourites = models.ManyToManyField('accounts.Post')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def admin_photo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.pic.url))
    admin_photo.short_description = "Profile Pic"
    admin_photo.allow_tags = True
    
    class Meta:
        ordering = ['-pk']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Profile, self).save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse("profile-detail", kwargs={"slug": self.slug})

class Notification(models.Model):
	NOTIFICATION_TYPES = ((1,'Like'),(2,'Comment'), (3,'Follow'))
    
	post = models.ForeignKey('accounts.Post', on_delete=models.CASCADE, related_name="noti_post", blank=True, null=True)
	sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="noti_from_user")
	user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="noti_to_user")
	notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
	text_preview = models.CharField(max_length=90, blank=True)
	date = models.DateTimeField(auto_now_add=True)
	is_seen = models.BooleanField(default=False)
    # def __str__(self):
    #     return self.notification_type + " notification of post " + " (" +  self.post + ")" + " posted by " + self.user

class Post(models.Model):
    uploaded_by = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE)
    msg = models.TextField()
    pic = models.ImageField(upload_to=post_image_directory_path, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    tags = TaggableManager(verbose_name='Hashtags', help_text='Tag your post here')
    # likes = models.IntegerField(default=0)
    # liked = models.ManyToManyField(CustomUser, related_name='likes')
    cr_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("", args=[str(self.id)])
    
    def __str__(self):
        return self.msg[0:20]

    # def num_likes(self):
    #     return self.liked.all().count()

    def admin_photo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.pic.url))
    admin_photo.short_description = "Post Picture"
    admin_photo.allow_tags = True

class PostFileContent(models.Model):
    uploaded_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='post_owner')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_image')
    file = models.FileField(upload_to=post_images_directory_path, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return self.post.msg[0:20]
    
class PostComment(models.Model):
    commented_by = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    msg = models.CharField(max_length=500)
    updated_at = models.DateTimeField(auto_now=True)
    cr_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.msg[0:20]

    def user_comment_post(sender, instance, *args, **kwargs):
        comment = instance
        post = comment.post
        text_preview = comment.msg[:90]
        sender = comment.commented_by
        notify = Notification(post=post, sender=sender, user=post.uploaded_by, text_preview=text_preview, notification_type=2)
        notify.save()

    def user_del_comment_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.commented_by
        notify = Notification.objects.filter(post=post, sender=sender, notification_type=2)
        notify.delete()

# LIKE_CHOICES = (
#     ('Like', 'Like'),
#     ('Unlike', 'Unlike'),
# )

class PostLike(models.Model):
    liked_by = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    # value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    cr_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s liked by %s" %(self.post, self.liked_by)

    def user_liked_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.liked_by
        notify = Notification(post=post, sender=sender, user=post.uploaded_by, notification_type=1)
        notify.save()

    def user_unlike_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.liked_by
        notify = Notification.objects.filter(post=post, sender=sender, notification_type=1)
        notify.delete()
    

class FollowUser(models.Model):
    follower = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='follower')

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import now
from taggit.managers import TaggableManager
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import FileExtensionValidator

def blog_thumbnail_directory_path(instance, filename):
    return 'user_{0}/blog/{1}/thumbnail/{2}'.format(instance.author.id, instance.title, filename)

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)

class Blog(models.Model):
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    thumbnail = models.ImageField(upload_to=blog_thumbnail_directory_path, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, blank=True)
    content = RichTextUploadingField()
    views= models.IntegerField(default=0)
    tags=TaggableManager(help_text="Tag your blog here")
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Blog Post'
        verbose_name_plural = 'Blog Posts'

    def __str__(self):
        return self.title + '- by ' + self.author.username

    def admin_photo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.thumbnail.url))
    admin_photo.short_description = "Blog Thumbnail"
    admin_photo.allow_tags = True

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Blog, self).save(*args,**kwargs)

class BlogComment(models.Model):
    user=models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    comment=models.TextField()
    post=models.ForeignKey(Blog, on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE, null=True)
    timestamp= models.DateTimeField(default=now)

    def __str__(self):
        return self.comment[0:13] + "---" + "by" + " " + self.user.username

    def admin_photo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.post.thumbnail.url))
    admin_photo.short_description = "Blog Thumbnail"
    admin_photo.allow_tags = True
    
    

    

accounts/templates/accounts/delete post.html
{% extends 'base.html' %}

{% block title %}Delete Post |
{% endblock title %}

{% block body %}
<div class="container mt-5 p-5">
    <div class="card bg-light p-3 rounded w-50">
        <div class="card-body">
            <h5 class="card-title fs-5 text-dark">Are you sure you want to delete your post "<b>{{object}}</b>" ?</h5>
            <form method="POST" style="font-family:cursive;">
                {% csrf_token %}
                <input type="submit" value="Confirm" class="btn btn-danger shadow-sm btn-block mt-3">
            </form>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/accounts/edit post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Post |
{% endblock title %}

{% block css %}
.form-group{
    margin-bottom:1.5rem;
}
label{
    display:inline-block;
    margin-bottom:0.5rem;
    font-family:'Baloo Tamma 2', cursive;
}
.card-body{
    padding:1.1rem;
}
{% endblock css %}

{% block body %}
<div class="container mt-5 p-5">
    <div class="card bg-light rounded p-3">
        <h3 class="card-heading text-dark fs-1" style="text-align:center;font-family:monospace;">Edit your Post</h3>
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-outline-primary">Edit</button>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/accounts/interests_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}
  <div class="container m-5 p-5">
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'home' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
  </div>
{% endblock %}

accounts/templates/accounts/notifications.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Notifications |
{% endblock title %}

{% block css %}
.card{
    position:relative;
}
.card .delete-notification{
    position:absolute;
    top:10px;
    right:10px;
}
{% endblock css %}


{% block body %}
<div class="container mt-5 p-5">
    <div class="d-flex align-items-center justify-content-center">
        {% for notification in notifications %}
            {% if notification.notification_type == 2 %}
                <div class="card w-50">
                    <div class="delete-notification">
                        <a href="{% url 'delete-notification' notification.id %}" class="btn btn-light btn-sm"><i class="far fa-times-circle"></i></a>
                    </div>
                    <div class="card-body">
                        <div class="d-flex flex-row align-items-center feed-text px-2"><a href="{% url 'profile-detail' notification.sender.profile.slug %}"><img class="rounded-circle" src="{{notification.sender.profile.pic.url}}" width="45"></a>
                        <div class="d-flex flex-column flex-wrap ml-2"><span class="fw-bold">{{notification.sender.get_full_name}}</span><small><span class="text-muted">@{{notification.sender.username}}</span></small><small><span class="text-black-50 time"><i class="far fa-clock"></i> {{notification.date|naturaltime}}</span></small></div>
                        <br><br><br>
                        <p class="float-start"><i style="font-family:calibri;">Commented:<i> <b>{{ notification.text_preview }}</b></p>
                        <img src="{{notification.post.pic.url}}" class="img-fluid img-responsive float-end" style="height:100px;width:100px;">
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
</div>
{% endblock body %}

accounts/templates/accounts/post detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}Post-{{post.id}} |
{% endblock title %}

{% block css %}
.time {
    font-size: 9px !important
}

.socials i {
    margin-right: 14px;
    font-size: 17px;
    color: #d2c8c8;
    cursor: pointer
}

.feed-image img {
    width: 100%;
    height: auto
}
{% endblock css %}

{% block body %}
<div class="container mt-5 mb-5 p-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <div class="feed p-2">
                <div class="bg-white border rounded mt-2">
                    <div>
                        <div class="d-flex flex-row justify-content-between align-items-center p-2 border-bottom">
                            <div class="d-flex flex-row align-items-center feed-text px-2"><a href="{% url 'profile-detail' post.uploaded_by.profile.slug %}"><img class="rounded-circle" src="{{post.uploaded_by.profile.pic.url}}" width="45"></a>
                                <div class="d-flex flex-column flex-wrap ml-2"><span class="fw-bold">{{post.uploaded_by.get_full_name}}</span><span class="text-black-50 time"><i class="far fa-clock"></i> {{post.cr_date|naturaltime}}</span></div>
                            </div>
                            {% ifequal request.user post.uploaded_by %}
                            <div class="dropdown dropstart">
                                <div class="feed-icon px-2"><i class="fa fa-ellipsis-v text-black-50" data-bs-toggle="dropdown" aria-expanded="false" data-bs-display="static"></i></div>
                                <ul class="dropdown-menu dropdown-menu-start dropdown-menu-md-end" aria-labelledby="dropdownMenuButton">
                                    <li><a class="dropdown-item" href="{% url 'post-edit' post.id %}">Edit Post</a></li>
                                    <li><a class="dropdown-item" href="{% url 'post-delete' post.id %}">Delete Post</a></li>
                                </ul>
                            </div>
                            {% endifequal %}
                        </div>
                    </div>
                    <div class="feed-image p-2 px-3"><img class="img-fluid img-responsive rounded" src="{{post.pic.url}}"></div>
                    <p class="mx-5 text-dark fs-6" style="font-family:calibri;">{{post.msg}}</p>
                    <P></p>
                    <p class="text-dark mx-5 mb-1">{% for tag in post.tags.all %}
                    <small><a href="{% url 'tag' tag.slug %}" class="text-primary">#{{tag}}</a></small>
                    {% endfor %}</p>
                    <div class="d-flex justify-content-between socials px-3 py-3">
                        <div class="d-inline-flex">
                            <a href="{% url 'profile-detail' request.user.profile.slug %}"><img class="img-fluid img-responsive rounded-circle d-block mr-3 ml-5" src="{{request.user.profile.pic.url}}" width="30"></a>
                            <form action="" method="POST" class="d-block d-inline-flex">
                            {% csrf_token %}
                                <input type="hidden" name="pk" value={{post.id}}>
                                {{form|crispy}}
                                <button type="submit" class="ml-3 btn btn-sm btn-light"><i class="ml-3 far fa-paper-plane text-dark fa-2x"></i></button>
                            </form>
                        </div>
                        <div>
                            {% if post.liked %}
                            <a href="{% url 'unlike' post.id %}"><i class="fa fa-thumbs-down text-danger"></i></a>
                            {% else %}
                            <a href="{% url 'like' post.id %}"><i class="fa fa-thumbs-up text-primary"></i></a>
                            {% endif %}                     
                            <i class="fa fa-comments-o"><span class="text-dark ml-1">{{post.postcomment_set.all.count}}</span></i>
                            {% if favourited is True %}
                            <a href="{% url 'favourite' post.id %}"><i class="fas fa-bookmark text-success"></i></a>
                            {% else %}
                            <a href="{% url 'favourite' post.id %}"><i class="far fa-bookmark text-success"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="bg-white border mt-2">
                    <div>
                        <div class="d-flex flex-row justify-content-between align-items-center p-2 border-bottom">
                            <div class="d-flex flex-row align-items-center feed-text px-2">
                                <div class="d-flex flex-column flex-wrap ml-2"><span class="fw-bold">Recent Comments</span></div>
                            </div>
                            <div class="feed-icon px-2"></div>
                        </div>
                    </div>
                    {% for comment in comments %}
                    <div class="p-2 px-3">
                        <div class="d-flex flex-row align-items-center feed-text px-2"><a href="{% url 'profile-detail' comment.commented_by.profile.slug %}"><img class="rounded-circle" src="{{comment.commented_by.profile.pic.url}}" width="45"></a>
                        <div class="d-flex flex-column flex-wrap ml-2"><span class="fw-bold">{{comment.commented_by.get_full_name}}</span><span class="text-black-50 time"><i class="far fa-clock"></i> {{comment.cr_date|naturaltime}}</span></div>
                        </div>
                        <p class="ml-5 text-dark px-5 fs-6 mb-3" style="font-family:calibri;">{{comment.msg}}</p>
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/accounts/post tag.html
{% extends 'base.html' %}

{% block title %}{{tag.slug|capfirst}} |
{% endblock title %}

{% block css %}
.intro {
     font-size: 16px;
     max-width: 500px;
     margin: 0 auto
 }

 .intro p {
     margin-bottom: 0
 }

 .people {
     padding: 50px 0;
     cursor: pointer
 }

 .item {
     margin-bottom: 30px
 }

 .item .box {
     text-align: center;
     background-repeat: no-repeat;
     background-size: cover;
     background-position: center;
     height: 280px;
     position: relative;
     overflow: hidden
 }

 .item .cover {
     position: absolute;
     top: 0;
     left: 0;
     width: 100%;
     height: 100%;
     background-color: rgba(31, 148, 255, 0.75);
     transition: opacity 0.15s ease-in;
     opacity: 0;
     padding-top: 80px;
     color: #fff;
     text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.15)
 }

 .item:hover .cover {
     opacity: 1
 }

 .item .name {
     font-weight: bold;
     margin-bottom: 8px
 }

 .item .title {
     text-transform: uppercase;
     font-weight: bold;
     color: #bbd8fb;
     letter-spacing: 2px;
     font-size: 13px;
     margin-bottom: 20px
 }

 .social {
     font-size: 18px
 }

 .social a {
     color: inherit;
     margin: 0 10px;
     display: inline-block;
     opacity: 0.7
 }

 .social a:hover {
     opacity: 1
 }
.bg {
    background-image: linear-gradient(#3F51B5, #1A237E);
     background-repeat: no-repeat;
     color: #000;
     overflow-x: hidden
}
{% endblock css %}

{% block body %}
<div class="container-fluid bg-success w-100 mt-5">
    <div class="d-flex m-5 p-5 align-items-center justify-content-center">
        <h1 style="font-size:100px;" class="text-light">#{{tag}}</h1>
    </div>
</div>
<div class="container bg rounded">
    <div class="row people d-flex justify-content-center">
        {% for post in posts %}
            <div class="col-md-4 col-lg-3 item">
                <a href="{% url 'post-detail' post.id %}">
                    <div class="box">
                        <img src="{{post.pic.url}}" alt="Post Image">
                        <div class="cover">
                            <h3 class="name">{{post.msg|truncatechars:10}}</h3>
                            <p class="title">{{post.uploaded_by.get_full_name}}</p>
                            <div class="social"><i class="fas fa-heart mr-2"></i>{{post.postlike_set.all.count}}&nbsp; &nbsp; &nbsp;<i class="fas fa-comments mr-2"></i>{{post.postcomment_set.all.count}}</div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock body %} 