PazarSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from accounts.views import activation_sent_view, activate, ProfileEditView, ProfileView, post_comment_create_and_list_view, like, unlike, favourite, PostDetail, likePost, unlikePost, tags, PostDeleteView, PostEditView, showNotifications, DeleteNotification

admin.site.site_header = "Pazar Admin"
admin.site.site_title = "Pazar Admin Portal"
admin.site.index_title = "Welcome to Pazar Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pazar.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),

    path('accounts/', include('allauth.urls')),
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='pazar/change-password.html',success_url='home'),name='change-password'),

    path('edit-profile/', ProfileEditView.as_view(), name="edit-profile"),
    path('profile/<int:id>/<slug:slug>', ProfileView.as_view(), name="profile"),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name="password_change"),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('posts/', post_comment_create_and_list_view, name="posts"),
    path('post/like/<int:pk>', like, name="like-post"),
    path('post/unlike/<int:pk>', unlike, name="unlike-post"),
    path('like-post/<int:pk>', likePost, name='like'),
    path('unlike-post/<int:pk>', unlikePost, name='unlike'),
    path('post/favourite/<int:pk>', favourite, name='favourite'),
    path('post/<int:pk>', PostDetail, name='post-detail'),
    path('post/tags/<slug:slug>', tags, name="tag"),
    path('post/<int:pk>/edit', PostEditView.as_view(), name="post-edit"),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('posts/notifications', showNotifications, name='show-notifications'),
    path('posts/notifications/<int:pk>/delete', DeleteNotification, name="delete-notification"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.bloghome, name="blog_home"),
    path('category/<slug:slug>', views.blogcategory, name="blog_category"),
    path('all-category', views.category, name="all_category"),
    path('article/<slug:slug>', views.blogPost, name="blog-post"),
    path('postComment', views.postComment, name="postComment"),
    path('tag/<slug:slug>/', views.tagged, name="tagged"),
    path('write-for-us', views.writeForUs, name="writeForUs"),
    path('search', views.search, name="search"),
    path('edit/<slug:slug>', views.BlogEditView.as_view(), name="edit-blog"),
    path('delete/<slug:slug>', views.BlogDeleteView.as_view(), name="delete-blog"),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import now
from taggit.managers import TaggableManager
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import FileExtensionValidator

def blog_thumbnail_directory_path(instance, filename):
    return 'user_{0}/blog/{1}/thumbnail/{2}'.format(instance.author.id, instance.title, filename)

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args,**kwargs)

class Blog(models.Model):
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    thumbnail = models.ImageField(upload_to=blog_thumbnail_directory_path, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, blank=True)
    content = RichTextUploadingField()
    views= models.IntegerField(default=0)
    tags=TaggableManager(help_text="Tag your blog here")
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Blog Post'
        verbose_name_plural = 'Blog Posts'

    def __str__(self):
        return self.title + '- by ' + self.author.username

    def admin_photo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.thumbnail.url))
    admin_photo.short_description = "Blog Thumbnail"
    admin_photo.allow_tags = True

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Blog, self).save(*args,**kwargs)

class BlogComment(models.Model):
    user=models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    comment=models.TextField()
    post=models.ForeignKey(Blog, on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE, null=True)
    timestamp= models.DateTimeField(default=now)

    def __str__(self):
        return self.comment[0:13] + "---" + "by" + " " + self.user.username

    def admin_photo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.post.thumbnail.url))
    admin_photo.short_description = "Blog Thumbnail"
    admin_photo.allow_tags = True
    
    

    

blog/forms.py
from django import forms
from .models import Blog
from django.forms import ModelForm

class BlogForm(forms.ModelForm):
    
    class Meta:
        model = Blog
        fields = ('title', 'category', 'thumbnail', 'content', 'tags',)
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Write Blog Title'}),
            'thumbnail':forms.FileInput(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(BlogForm, self).__init__(*args, **kwargs)
        self.fields['tags'].widget.attrs['data-role'] = 'tagsinput'
    

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Category, Blog, BlogComment
from django.contrib import messages
from blog.templatetags import extras
from django.core.paginator import Paginator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from .forms import BlogForm
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.
def bloghome(request):
    category = Category.objects.order_by('name')[:12]
    blog = Blog.objects.order_by('?')[:3]
    return render(request, 'blog/blog home.html', {'category':category, 'blog':blog})

def blogcategory(request, slug):
    category = Category.objects.filter(slug=slug).first()
    blogpost = Blog.objects.filter(category=category)
    return render(request, 'blog/blog category.html', {'blogpost':blogpost, 'category':category})

def category(request):
    category = Category.objects.order_by('name')
    blog = Blog.objects.order_by('timestamp')
    page = request.GET.get('page', 1)

    paginator = Paginator(blog, 20)
    try:
        blog = paginator.page(page)
    except PageNotAnInteger:
        blog = paginator.page(1)
    except EmptyPage:
        blog = paginator.page(paginator.num_pages)
    return render(request, 'blog/all category.html', {'category':category, 'blog':blog})

def blogPost(request, slug): 
    post=Blog.objects.filter(slug=slug).first()
    post.views= post.views +1
    post.save()
    comments= BlogComment.objects.filter(post=post, parent=None)
    replies= BlogComment.objects.filter(post=post).exclude(parent=None)
    replyDict = {}
    for reply in replies:
        if reply.parent.id not in replyDict.keys():
            replyDict[reply.parent.id]=[reply]
        else:
            replyDict[reply.parent.id].append(reply)
    context={'post':post, 'comments': comments, 'user': request.user, 'replyDict':replyDict}
    return render(request, "blog/blogPost.html", context)

def postComment(request):
    if request.method == "POST":
        comment=request.POST.get('comment')
        user=request.user
        postSno =request.POST.get('postSno')
        post= Blog.objects.get(id=postSno)
        parentSno= request.POST.get('parentSno')
        if parentSno == "":
            comment=BlogComment(comment= comment, user=user, post=post)
            comment.save()
            messages.success(request, "Your comment has been posted successfully!")
        else:
            parent= BlogComment.objects.get(id=parentSno)
            comment=BlogComment(comment= comment, user=user, post=post , parent=parent)
            comment.save()
            messages.success(request, "Your reply has been posted successfully!")
    return redirect(f"/blog/article/{post.slug}")

def tagged(request, slug):
    category = Category.objects.order_by('name')
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Blog.tags.most_common()[:5]
    posts = Blog.objects.filter(tags=tag)
    context = {
        'tag':tag,
        'common_tags':common_tags,
        'blog':posts,
        'category':category,
    }
    return render(request, 'blog/all category.html', context)

@login_required(login_url='/account/login')
def writeForUs(request):
    form = BlogForm()
    if request.method == "POST":
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            form.save_m2m()
            messages.success(request, "Your blog has been published successfully!")
    else:
        form = BlogForm()
    context = {
        'form':form
    }
    return render(request, 'blog/write for us.html', context)

def search(request):
    query=request.GET['query']
    if len(query)>78 or len(query)<1:
        allPosts=Blog.objects.none()
    else:
        allPostsTitle= Blog.objects.filter(title__icontains=query)
        allPostsContent =Blog.objects.filter(content__icontains=query)
        allPosts=  allPostsTitle.union(allPostsContent)
    if allPosts.count()==0:
        messages.warning(request, "No search results found. Please refine your query.")
    params={'allPosts': allPosts, 'query': query}
    return render(request, 'blog/search.html', params)

class BlogEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog edit.html'
    success_message = 'Your blog has been updated!'
    success_url = reverse_lazy('blog-list')

class BlogDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Blog
    template_name = 'blog/blog delete.html'
    fields = '__all__'
    success_message = 'Your blog has been deleted successfully!'
    success_url = reverse_lazy('blog-list')

blog/templates/blog/all category.html
{% extends 'blog/blog base.html' %}
{% load static %}

{% block title %}All Blog Category |
{% endblock title %}

{% block categoryactive %}active
{% endblock categoryactive %}

{% block css %}
.card-img {
  border-bottom-left-radius: 0px;
  border-bottom-right-radius: 0px;
}

.card-img-overlay{
  width:0;
}

.card-title {
  margin-bottom: 0.3rem;
}

.cat {
  display: inline-block;
  margin-bottom: 1rem;
}

.fa-users {
  margin-left: 1rem;
}

.card-footer {
  font-size: 0.8rem;
}

.card{
  box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);
  transition: box-shadow .25s;
}

.card:hover {
  box-shadow: 0 8px 17px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19);
}
.card-title{
  transition:ease 0.5s;
}
.card-title:hover{
  color:#0dcaf0;
}
.blog-body{
  font-family: charter, Georgia, Cambria, "Times New Roman", Times, serif;
}
.blog-stats{
  font-family: 'Calibri', sans-serif !important;
}
#bgAnimate{
  width: 100%;
  height: 500px;
  background: linear-gradient(-45deg, #3f51b1 0%, #5a55ae 13%, #7b5fac 25%, #8f6aae 38%, #a86aa4 50%, #cc6b8e 62%, #f18271 75%, #f3a469 87%, #f7c978 100%);;
  background-size: 400% 400%;
  position: relative;
  animation: bgAnimate 7.5s ease-in-out infinite;
  display: flex;
  justify-content: center;
  align-items: center;
}
@keyframes bgAnimate{
  0%{
    background-position: 0 50%;
  }
  50%{
    background-position: 100% 50%;
  }
  100%{
    background-position: 0 50%;
  }
}
.circles{
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.circles li{
    position: absolute;
    display: block;
    list-style: none;
    width: 20px;
    height: 20px;
    background: rgba(255, 255, 255, 0.2);
    animation: rotate 25s linear infinite;
    bottom: -150px;
    
}

.circles li:nth-child(1){
    left: 25%;
    width: 80px;
    height: 80px;
    animation-delay: 0s;
}


.circles li:nth-child(2){
    left: 10%;
    width: 20px;
    height: 20px;
    animation-delay: 2s;
    animation-duration: 12s;
}

.circles li:nth-child(3){
    left: 70%;
    width: 20px;
    height: 20px;
    animation-delay: 4s;
}

.circles li:nth-child(4){
    left: 40%;
    width: 60px;
    height: 60px;
    animation-delay: 0s;
    animation-duration: 18s;
}

.circles li:nth-child(5){
    left: 65%;
    width: 20px;
    height: 20px;
    animation-delay: 0s;
}

.circles li:nth-child(6){
    left: 75%;
    width: 110px;
    height: 110px;
    animation-delay: 3s;
}

.circles li:nth-child(7){
    left: 35%;
    width: 150px;
    height: 150px;
    animation-delay: 7s;
}

.circles li:nth-child(8){
    left: 50%;
    width: 25px;
    height: 25px;
    animation-delay: 15s;
    animation-duration: 45s;
}

.circles li:nth-child(9){
    left: 20%;
    width: 15px;
    height: 15px;
    animation-delay: 2s;
    animation-duration: 35s;
}

.circles li:nth-child(10){
    left: 85%;
    width: 150px;
    height: 150px;
    animation-delay: 0s;
    animation-duration: 11s;
}



@keyframes rotate {

    0%{
        transform: translateY(0) rotate(0deg);
        opacity: 1;
        border-radius: 0;
    }

    100%{
        transform: translateY(-1000px) rotate(720deg);
        opacity: 0;
        border-radius: 50%;
    }

}
.content h2:nth-child(1){
    color:transparent;
    -webkit-text-stroke:2px #03a9f4;
}
.content h2:nth-child(2){
    color:#03a9f4;
    animation: textanimated 4s ease-in-out infinite;
}
@keyframes textanimated{
    0%, 100%{
        clip-path:polygon(0% 45%, 15% 44%, 32% 50%, 54% 60%, 70% 61%, 84% 59%, 100% 52%, 100% 100%, 0% 100%);
    }
    50%{
        clip-path:polygon(0 60%, 16% 65%, 34% 66%, 51% 62%, 67% 50%, 84% 45%, 100% 46%, 100% 100%, 0% 100%);
    }
}
{% endblock css %}

{% block content %}
<section id="bgAnimate">
  <div class="d-flex justify-content-center text-light content">
    <h2 style="position:absolute;top:200px;font-family: 'Poppins', sans-serif;font-size:8em;">Blogs</h2>
    <h2 style="position:absolute;top:200px;font-family: 'Poppins', sans-serif;font-size:8em;">Blogs</h2>
  </div>
  <ul class="circles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
</section>
<div class="container mt-3">
  <div class="row mb-2">
    <div class="col-md-10">
      <h2 class="fs-1 text-dark" style="font-family:sans;">All Blogs</h2>
      <div class="row product-row mx-auto mb-2">
          {% for blog in blog %}
            <div id="{{ blog.id }}" class="col-md-4 mb-4">
              <div class="card" data-aos="zoom-in">
                <img class="card-img card-img-top" src="{{blog.thumbnail.url}}" alt="{{blog.title}}">
                <div class="card-img-overlay">
                  <a href="#" class="btn btn-light btn-sm" style="font-family: 'Yusei Magic', sans-serif;">{{blog.category}}</a>
                </div>
                <div class="card-body">
                  <a href="{% url 'blog-post' blog.slug %}" class="text-dark" style="text-decoration:none;"><h4 class="card-title">{{blog.title}}</h4></a>
                  <small class="text-muted cat">
                    <i class="far fa-clock text-info" style="margin-right:4px;"></i>{{blog.timestamp|date:"M j"}}&nbsp &nbsp
                    <i class="far fa-comment text-info"></i> {{blog.blogcomment_set.count}} comments &nbsp &nbsp
                    <i class="far fa-eye text-info"></i> {{blog.views}}
                  </small>
                  <p class="card-text blog-body">{{blog.content|safe |truncatewords:10}}</p>
                  <a href="{% url 'blog-post' blog.slug %}" class="btn btn-dark blog-stats">Read article</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        {% if blog.has_other_pages %}
                    <ul class="pagination mt-3">
                      {% if blog.has_previous %}
                        <li class="page-item">
                        <a class="page-link" href="?page={{blog.previous_page_number}}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        </a>
                        </li>
                      {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a></li>
                      {% endif %}
                      {% for i in blog.paginator.page_range %}
                        {% if blog.number == i %}
                          <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                        {% else %}
                          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                        {% endif %}
                      {% endfor %}
                      {% if blog.has_next %}
                        <li class="page-item">
                        <a class="page-link" href="?page={{blog.next_page_number}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        </a>
                        </li>
                      {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</a></li>
                      {% endif %}
                    </ul>
                  {% endif %}
    </div>
    <div class="col-md-2">
        <h4 style="font-family:cursive;">All Category</h4>
        <ul class="list-group mb-2">
          {% for category in category %}
            <li class="list-group-item"><a href="{% url 'blog_category' category.slug %}" style="font-family: 'Yusei Magic', sans-serif;text-decoration:none;">{{category.name}}</a></li>
          {% endfor %}
        </ul>
        <h4 style="font-family:cursive;">Common Tags</h4>
        <ul class="list-group mb-2 mt-2">
          {% for mt in common_tags %}
            <li class="list-group-item"><a href="{% url 'tagged' tag.slug %}" class="btn btn-success btn-sm">{{mt}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/blog/blog category.html
{% extends 'blog/blog base.html' %}
{% load static %}

{% block title %}{{category.name}} |
{% endblock title %}

{% block categoryactive %}active
{% endblock categoryactive %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'CSS/bg animation.css' %}">
{% endblock extra_head %}

{% block css %}
.post-body{
    font-family: charter, Georgia, Cambria, "Times New Roman", Times, serif;
}
.content h2:nth-child(1){
    color:transparent;
    -webkit-text-stroke:2px #03a9f4;
}
.content h2:nth-child(2){
    color:#03a9f4;
    animation:animated 4s ease-in-out infinite;
}
@keyframes animated{
    0%, 100%{
        clip-path:polygon(0% 45%, 15% 44%, 32% 50%, 54% 60%, 70% 61%, 84% 59%, 100% 52%, 100% 100%, 0% 100%);
    }
    50%{
        clip-path:polygon(0 60%, 16% 65%, 34% 66%, 51% 62%, 67% 50%, 84% 45%, 100% 46%, 100% 100%, 0% 100%);
    }
}
{% endblock css %}

{% block content %}
	<div class="animation-area">
        <div class="d-flex justify-content-center text-light content">
            <h2 style="position:absolute;top:250px;font-family: 'Poppins', sans-serif;font-size:4em;">{{category.name}}</h2>
            <h2 style="position:absolute;top:250px;font-family: 'Poppins', sans-serif;font-size:4em;">{{category.name}}</h2>
        </div>
		<ul class="box-area">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
<div class="container mt-5">
    <h2>{{category.name}} Blogs</h2>
    <div class="row mb-2">
        {% for blogpost in blogpost %}
            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary" style="font-family: 'Montserrat', sans-serif;">{{blogpost.category}}</strong>
                        <a href="{% url 'blog-post' blogpost.slug %}" class="text-dark" style="text-decoration:none;font-family:serif;"><h3 class="mb-0">{{blogpost.title}}</h3></a>
                        <div class="mb-1 text-muted" style="font-family: 'Yusei Magic', sans-serif;">{{blogpost.timestamp|date:"F j Y"}}</div>
                            <p class="card-text mb-auto post-body">{{blogpost.content|safe|truncatewords:10}}</p>
                            <a href="{% url 'blog-post' blogpost.slug %}" class="stretched-link" style="font-family: 'Yusei Magic', sans-serif;text-decoration:none;">Continue reading <i class="fas fa-angle-double-right"></i></a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            {% if blogpost.thumbnail %}
                                <img src="{{blogpost.thumbnail.url}}" class="bd-placeholder-img" height="250" width="250">
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/blog delete.html
{% extends 'blog/blog base.html' %}

{% block title %}Delete Blog |
{% endblock title %}

{% block css %}
em{
    font-family:Calibri;
}
{% endblock css %}

{% block content %}
<div class="container mt-5 p-5">
    <h2 class="title">Delete Blog</h2>
    <form method="POST" style="font-family:cursive;">
        {% csrf_token %} 
        <em>Are you sure you want to delete <b>"{{ object }}"</b> ?</em><br>
        <input type="submit" value="Confirm" class="btn btn-danger shadow-sm btn-block mt-3">
        <a href="/myBlogs" class="btn btn-warning btn-block shadow-sm mt-3 ms-2"><i class="fa fa-arrow-circle-left me-2"></i>No, take me back!</a>
    </form> 
</div>
{% endblock content %}

blog/templates/blog/blog edit.html
{% extends 'blog/blog base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Blog |
{% endblock title %}

{% block categoryactive %}active
{% endblock categoryactive %}

{% block css %}
body{
    overflow-x:hidden;
}
.container{
    overflow:hidden;
}
.form-group{
    margin-bottom:1.5rem;
    font-family: 'Calibri', sans-serif;
}
label{
    display:inline-block;
    margin-bottom:0.5rem;
    font-family: 'Baloo Tamma 2', cursive;
}
.title{
    font-family: 'Baloo Tamma 2', cursive;
}
{% endblock css %}

{% block content %}
<div class="container mt-5 p-5">
    <h2 class="title">Edit Blog</h2>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary btn-lg">Save Changes</button>
    </form>
    {{form.media}}
</div>
{% endblock content %}

blog/templates/blog/search.html
{% extends 'blog/blog base.html' %}

{% block title %}Search Results |
{% endblock title %}

{% block css %}
.row{
    --bs-gutter-x:0;
}
.text-muted{
    font-family: 'Calibri', sans-serif !important;
}
.card-text{
    font-family: charter, Georgia, Cambria, "Times New Roman", Times, serif;
}
{% endblock css %}

{% block content %}
<div class="container my-5 p-5">
    <h2>Search results for <b>{{query}}</b> : </h2>
    {% if allPosts|length < 1 %}
   <p><i class="fs-5">No search results</i></p>
    <i>Your search query:</i> <b>{{query}}</b> did not match any documents.<br>
    <b>Suggestions:</b>
    <ul style="font-family: 'Calibri', sans-serif;">
        <li>Make sure that all words are spelled correctly.</li>
        <li>Try more general keywords.</li>
        <li> Try fewer keywords.</li>
        <li> Try different keywords.</li>
    </ul>
    {% endif %}
    {% for post in allPosts  %}
    <div class="row border rounded flex-md-row mb-4 shadow-sm h-md-250 my-4">
        <div class="col p-3 d-flex flex-column">
            <strong class="d-inline-block mb-2 text-primary" style="font-family: 'Montserrat', sans-serif;">{{post.category}}</strong>
            <h3 class="mb-0">{{post.title}}</h3>
            <div class="mb-1 text-muted">{{post.timestamp|date:"M j, Y"}}</div>
            <div class="card-text mt-1 mb-1">{{post.content|safe|truncatechars:300}}</div>
            <div class="my-2">
            	<a href="{% url 'blog-post' post.slug %}" role="button" class="btn btn-info btn-sm" style="font-family:cursive;">Continue reading...</a>
            </div>          
        </div>
        <div class="col-auto d-none d-lg-block">
            <img src="{{post.thumbnail.url}}" class="bd-placeholder-img" height="250" width="250">
        </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}